### ISSUE TITLE
base.rb throws git errors when site is not in a git repo

### ISSUE THREAD

**Issue by johlym** [ayushn21/bridgetown-sitemap#1]
I originally brought this up in https://github.com/bridgetownrb/bridgetown/issues/490 but after some testing, was able to narrow it down to this plugin. 

There are cases where a Bridgetown site may be deployed without existing in an active git repo (`.git` folder present), and as such, `git` commands will not work and throw errors. For sites with a lot of content, this creates a wall of git error noise. 

https://github.com/ayushn21/bridgetown-sitemap/blob/main/lib/bridgetown/resource/base.rb#L12 - This logic should consider if git is available and if not, skip it.

**Comment by ayushn21** [comment]
Thanks for raising this @johlym, I'll work out a fix :)

**Comment by ayushn21** [comment]
Should be fixed by https://github.com/ayushn21/bridgetown-sitemap/commit/dd1bc493d7c78f780b3bae28364cbfb07593a07d. Let me know if the issue persists :).

I'll create a bugfix release for this shortly.

**Comment by ayushn21** [comment]
Released in v1.1.2
